### ISSUE TITLE
isActivePath binding handler

### ISSUE THREAD

**Issue by gandrisl** [Profiscience/ko-component-router#209]
Would be nice to have binding handler like this:
```javascript
ko.bindingHandlers.isActivePath = {
        init(el, valueAccessor, allBindings, viewModel, bindingCtx) {
            const router = ko.router.Router;
            const isActivePath = ko.router.isActivePath;
            var activePathCSSClass = allBindings.get("pathActiveClass") || router.config.activePathCSSClass;
            router.initialized.then(() => {
                var route = ko.pureComputed(() => traversePath(getRouter(bindingCtx), ko.unwrap(valueAccessor())));
                ko.applyBindingsToNode(el,
                    {
                        css: {
                            [activePathCSSClass]: ko.pureComputed(() => isActivePath(route()))
                        }
                    });
            });
        }
    };
```

**Comment by caseyWebb** [comment]
This is a good idea.

Would you be willing to write a spec for this and submit a PR?

**Comment by gandrisl** [comment]
I was unable to build the source. I get this error during a build:

```
C:/Users/gandris/ko-component-router/tasks/stats.js:34
async function getModuleStats(task) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.<anonymous> (C:/Users/gandris/ko-component-router/taskfile.js:6:17)
    at new Taskr (C:/Users/gandris/ko-component-router/node_modules/taskr/lib/taskr.js:21:39)
    at Object.<anonymous> (C:/Users/gandris/ko-component-router/node_modules/taskr/lib/cli/spawn.js:35:9)
    at undefined.tryCatcher (C:/Users/gandris/ko-component-router/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:/Users/gandris/ko-component-router/node_modules/bluebird/js/release/generators.
js:97:49)
```

**Comment by caseyWebb** [comment]
Building requires Node 7.6 or above
