### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#70]
I'm trying to create a few tests but I can't get the tests to run. 

After cloning the repo and doing a `npm install`, when I run `npm run test` I get the following issue with babel:

```
D:\Repos\tmp\ko-component-router {git}{hg}
{lamb} npm run test

> ko-component-router@3.8.3 test D:\Repos\tmp\ko-component-router
> karma start

Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.13.1
Time: 2774ms

ERROR in ./test.js
Module build failed: ReferenceError: Unknown plugin "transform-regenerator" specified in "base" at 3, attempted to resolve relative to "D:\\Repos\\tmp\\ko-component-router"
    at D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\options\option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:20)
    at OptionManager.mergeOptions (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\options\option-manager.js:300:36)
    at OptionManager.init (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\options\option-manager.js:488:10)
    at File.initOptions (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\index.js:223:65)
    at new File (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\file\index.js:140:24)
    at Pipeline.transform (D:\Repos\tmp\ko-component-router\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\Repos\tmp\ko-component-router\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\Repos\tmp\ko-component-router\node_modules\babel-loader\index.js:88:12)
```

Any suggestion?

**Comment by caseyWebb** [comment]
whoops...

run `npm install babel-plugin-transform-regenerator`

fixing in 46d68646c57a0027bd27030f7c0d19f3e1080815

**Comment by caseyWebb** [comment]
Changed Travis settings to build on push to avoid this again.
